Repository mash-up-kr/MAC_Web, pull requests merged in 2021-02, with the labels that each got.

#11 styled theme작성
  public/index.html
  src/App.tsx
  src/components/.gitkeep
  src/constants/.gitkeep
  src/constants/colors.ts
  src/constants/media.ts
  src/global-styles.ts
  src/index.tsx
  src/pages/.gitkeep
Labels: setting

#13 feat: svg컴포넌트 작성
  package.json
  src/elements/SVGIcon/SVGIcon.styled.ts
  src/elements/SVGIcon/SVGIcon.tsx
  src/elements/SVGIcon/index.ts
  yarn.lock
Labels: feature

#16 고민리스트 UI작성
  src/components/ConcernItem/ConcernItem.styled.ts
  src/components/ConcernItem/ConcernItem.tsx
  src/components/ConcernItem/index.ts
  src/components/ConcernList/ConcernList.styled.ts
  src/components/ConcernList/ConcernList.tsx
  src/components/ConcernList/index.ts
  src/constants/colors.ts
  src/containers/ConcernListContainer.tsx
  src/pages/Concerns.tsx
Labels: feature

#18 main 브랜치에 푸쉬할 때 S3 정적 웹호스팅으로 배포합니다.
  .github/workflows/react-build-deploy.yml
Labels: enhancement
